users:
  user_you:
    foreground: Blue
    is_bold: true
  user_root:
    foreground: Red
  user_other:
    foreground: White
  group_yours:
    foreground: Cyan
  group_other:
    foreground: BrightBlue
  group_root:
    foreground: Red

filekinds:
  normal:
    foreground: White
  directory:
    foreground: Blue
    is_bold: true
  symlink:
    foreground: Cyan
  executable:
    foreground: BrightBlue
    is_bold: true
  mount_point:
    foreground: BrightBlue
    is_bold: true

git:
  new:
    foreground: Cyan
  modified:
    foreground: Blue
  deleted:
    foreground: Red
  renamed:
    foreground: BrightBlue
  ignored:
    foreground: BrightBlack
  conflicted:
    foreground: Yellow
    is_bold: true

git_repo:
  branch_main:
    foreground: Blue
    is_bold: true
  branch_other:
    foreground: Cyan
  git_clean:
    foreground: Green
  git_dirty:
    foreground: Yellow

file_type:
  image:
    foreground: Magenta
  video:
    foreground: BrightMagenta
  music:
    foreground: Cyan
  crypto:
    foreground: Green
  document:
    foreground: BrightBlue
  compressed:
    foreground: Red
  temp:
    foreground: BrightBlack
  compiled:
    foreground: Yellow
  build:
    foreground: Yellow
    is_underline: true
  source:
    foreground: BrightBlue

date:
  foreground: BrightBlack

header:
  foreground: BrightBlue
  is_bold: true

size:
  major:
    foreground: Blue
  minor:
    foreground: Cyan
  number_byte:
    foreground: White
  number_kilo:
    foreground: White
  number_mega:
    foreground: BrightBlue
  number_giga:
    foreground: Cyan
  number_huge:
    foreground: Magenta
  unit_byte:
    foreground: BrightBlack
  unit_kilo:
    foreground: BrightBlack
  unit_mega:
    foreground: BrightBlack
  unit_giga:
    foreground: BrightBlack
  unit_huge:
    foreground: BrightBlack
