set runtimepath^=~/.config/vim
set nocompatible
filetype plugin indent on
syntax on

set background=dark
set termguicolors
set mouse=a
set number
set relativenumber
set ruler
set showcmd
set hidden
set splitbelow
set splitright
set ignorecase
set smartcase
set incsearch
set hlsearch
set clipboard=unnamedplus
set tabstop=4
set shiftwidth=4
set softtabstop=4
set expandtab
set smartindent
set undofile
set updatetime=250
set scrolloff=4
set sidescrolloff=4
set signcolumn=yes
set cursorline
set wildmenu
set wildmode=longest:full,full
set backspace=indent,eol,start
set list
set listchars=tab:»·,trail:·,nbsp:␣
set t_Co=256

let &undodir = expand('~/.config/vim/undo//')
call mkdir(&undodir, 'p')

colorscheme installations-configurations
