BREW_CONFIGURE_STEPS=(
  "caddy-configure"
  "caddy-trust"
  "podman-configure"
)
BREW_BOOTSTRAP_STEPS=(
  "brew-install"
  "brew-upgrade"
  "brew-configure"
)
BREW_BOOTSTRAP_SERVICE_ACTION="start"
BREW_MANAGED_SERVICE_SCRIPTS=(
  "caddy-service"
)
