DOCK_AUTO_HIDE=true
DOCK_REORDER_SPACES_BY_RECENT_USE=false
AC_POWER_SYSTEM_SLEEP_MINUTES=0
SYSTEM_DOCK_DOMAIN="com.apple.dock"
SYSTEM_DOCK_AUTO_HIDE_KEY="autohide"
SYSTEM_DOCK_REORDER_SPACES_KEY="mru-spaces"
SYSTEM_PMSET_AC_POWER_SECTION="AC Power"
SYSTEM_PMSET_PORTABLE_SLEEP_SCOPE="-c"
SYSTEM_PMSET_NON_PORTABLE_SLEEP_SCOPE="-a"
