#!/usr/bin/env bash
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/../../.." && pwd)"
SCRIPT_FILE="$ROOT/scripts/podman/macos/podman-configure"
MACHINE_CONFIG_HELPERS_FILE="$ROOT/lib/shell/shared/machine-config.sh"
test -f "$ROOT/config/podman/macos/podman-machine-settings-shared.conf"
test -f "$ROOT/config/podman/macos/podman-runtime-settings-shared.conf"
test -f "$SCRIPT_FILE"
test -f "$MACHINE_CONFIG_HELPERS_FILE"
test -f "$ROOT/lib/shell/shared/homebrew.sh"
grep -q 'scripts/brew/macos/brew-bootstrap' "$ROOT/scripts/podman/macos/podman-check"
grep -q 'may pull the configured verification image' "$ROOT/scripts/podman/macos/podman-check"
grep -q '^PODMAN_DIAGNOSE_OUTPUT_DIR=' "$ROOT/config/podman/macos/podman-runtime-settings-shared.conf"
grep -q '^PODMAN_DIAGNOSE_EVENT_WINDOWS=' "$ROOT/config/podman/macos/podman-runtime-settings-shared.conf"
grep -q '^PODMAN_DIAGNOSE_HOST_COMMANDS=' "$ROOT/config/podman/macos/podman-runtime-settings-shared.conf"
! grep -q '^PODMAN_SOURCE_RELATIVE_PATH=' "$ROOT/config/podman/macos/podman-runtime-settings-shared.conf"
grep -q 'Usage: .*\[diagnose\]' "$ROOT/scripts/podman/macos/podman-check"
grep -q '^\[machine\]$' "$ROOT/config/podman/macos/podman-machine-settings-shared.conf"
grep -q '^cpus=4$' "$ROOT/config/podman/macos/podman-machine-settings-shared.conf"
grep -q '^memory=8192$' "$ROOT/config/podman/macos/podman-machine-settings-shared.conf"
grep -q '^disk_size=60$' "$ROOT/config/podman/macos/podman-machine-settings-shared.conf"
grep -q '^rootful=false$' "$ROOT/config/podman/macos/podman-machine-settings-shared.conf"
grep -q '^PODMAN_MACHINE_NAME_DEFAULT=' "$ROOT/config/podman/macos/podman-runtime-settings-shared.conf"
grep -q '^PODMAN_RECONCILE_EXISTING_MACHINE=true$' "$ROOT/config/podman/macos/podman-runtime-settings-shared.conf"
grep -q '^PODMAN_START_MACHINE_ON_CREATE=true$' "$ROOT/config/podman/macos/podman-runtime-settings-shared.conf"
grep -q '^PODMAN_START_MACHINE_FOR_VERIFICATION=true$' "$ROOT/config/podman/macos/podman-runtime-settings-shared.conf"
grep -q '^PODMAN_DISK_SIZE_UPDATE_POLICY="grow-only"$' "$ROOT/config/podman/macos/podman-runtime-settings-shared.conf"
grep -q 'Unsupported Podman disk-size update policy' "$SCRIPT_FILE"
grep -q '^PODMAN_CHECK_IMAGE="docker.io/library/alpine:3.22"$' "$ROOT/config/podman/macos/podman-runtime-settings-shared.conf"
grep -q 'source_layered_scoped_config "config/podman" "macos" "podman-runtime-settings" "conf"' "$ROOT/scripts/podman/macos/podman-check"
grep -q 'source_layered_scoped_config "config/podman" "macos" "podman-runtime-settings" "conf"' "$ROOT/scripts/podman/macos/podman-configure"
grep -q 'shared_scoped_config_path "config/podman" "macos" "podman-machine-settings" "conf"' "$ROOT/scripts/podman/macos/podman-configure"
grep -q 'host_scoped_config_path "config/podman" "macos" "podman-machine-settings" "conf"' "$ROOT/scripts/podman/macos/podman-configure"
grep -q 'Defaults to the configured machine name' "$ROOT/scripts/podman/macos/podman-configure"
! grep -q '^machine_setting_option_name() {$' "$SCRIPT_FILE"
! grep -q '^machine_setting_label() {$' "$SCRIPT_FILE"
! grep -q '^machine_setting_desired_value() {$' "$SCRIPT_FILE"
! grep -q '^set_machine_setting_desired_value() {$' "$SCRIPT_FILE"
! grep -q '^machine_setting_current_value() {$' "$SCRIPT_FILE"
if grep -q '^desired_machine_settings_summary() {$' "$SCRIPT_FILE"; then
  printf 'assertion failed: podman-configure should not keep unused desired-machine summary helpers\n' >&2
  exit 1
fi
echo "Podman checks passed (repository-only coverage)"
