# macOS system overrides for host 'maravyn' and user 'ezirius'.
#
# This file applies to host 'maravyn' for user 'ezirius' under configs/macos/system/.
# It is the host-specific, specific-user layer in the system config resolution order.

# DOCK_AUTO_HIDE=true
# DOCK_REORDER_SPACES_BY_RECENT_USE=false
# AC_POWER_SYSTEM_SLEEP_MINUTES=0

TIME_ZONE_AUTO_BY_LOCATION=false
TIME_ZONE="Africa/Johannesburg"
# CLOCK_24_HOUR=true

SSH_REMOTE_LOGIN_ENABLED=true
SSHD_ALLOW_USERS="ezirius"
# SSHD_LOGIN_KEY_FILES="maldoria-iparia-ezirius-login.pub maldoria-ipirus-ezirius-login.pub"
SSHD_LOGIN_KEY_FILES="maravyn-iparia-ezirius-login.pub maravyn-ipirus-ezirius-login.pub maravyn-maldoria-ezirius-login.pub"
# SSHD_LOGIN_KEY_FILES="norbert-iparia-ezirius-login.pub norbert-ipirus-ezirius-login.pub norbert-maldoria-ezirius-login.pub"
