color_theme = "tokyo-night"
theme_background = true
truecolor = true
vim_keys = true
rounded_corners = true
proc_gradient = true
proc_colors = true
show_cpu_freq = true
show_uptime = true
show_disks = true
mem_graphs = true
graph_symbol = "braille"
clock_format = "%X"
