#!/usr/bin/env bash
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
SCRIPT_FILE="$ROOT/scripts/macos/brew-upgrade"
test -f "$SCRIPT_FILE"
grep -q 'parse_brewfile_entries' "$ROOT/lib/shell/common.sh"
grep -q 'brew update 2>&1 | tee "\$BREW_UPDATE_OUTPUT_FILE"' "$SCRIPT_FILE"
grep -q 'Homebrew metadata' "$SCRIPT_FILE"
grep -q 'upgrade_brewfile_entries' "$SCRIPT_FILE"
grep -q 'parse_brewfile_entries' "$SCRIPT_FILE"
grep -q 'shared_platform_config_path "config/brew" "Brewfile"' "$SCRIPT_FILE"
grep -q 'entry_is_outdated' "$SCRIPT_FILE"
! grep -q 'brew bundle install --file=' "$SCRIPT_FILE"
grep -q 'entry_is_outdated "brew" "\$entry_name"' "$SCRIPT_FILE"
grep -q 'brew upgrade "\$entry_name"' "$SCRIPT_FILE"
grep -q 'entry_is_outdated "cask" "\$entry_name"' "$SCRIPT_FILE"
grep -q 'brew upgrade --cask "\$entry_name"' "$SCRIPT_FILE"
echo "Brew upgrade checks passed"
