#!/usr/bin/env bash
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
SCRIPT_FILE="$ROOT/scripts/macos/caddy-service"
CONFIG_FILE="$ROOT/config/caddy/shared-macos.conf"
test -f "$SCRIPT_FILE"
test -f "$CONFIG_FILE"
grep -q '^CADDY_SERVICE_NAME=' "$CONFIG_FILE"
! grep -q '^CADDY_LISTENER_PORT=' "$CONFIG_FILE"
grep -q '^validate_runtime_config() {$' "$SCRIPT_FILE"
grep -q '^resolve_listener_port() {$' "$SCRIPT_FILE"
grep -q 'grep -E' "$SCRIPT_FILE"
grep -q '^port_in_use() {$' "$SCRIPT_FILE"
grep -q '^  local port$' "$SCRIPT_FILE"
grep -q '^  port="\$(resolve_listener_port)"$' "$SCRIPT_FILE"
grep -q '^service_started() {$' "$SCRIPT_FILE"
grep -q '^  brew services list | grep -Eq ' "$SCRIPT_FILE"
grep -q '^  start)$' "$SCRIPT_FILE"
grep -q '^case "\$ACTION" in$' "$SCRIPT_FILE"
grep -q '^  stop|status) ;;$' "$SCRIPT_FILE"
grep -q '^  \*) validate_runtime_config ;;$' "$SCRIPT_FILE"
grep -q '^      if ! brew services start "\$CADDY_SERVICE_NAME"; then$' "$SCRIPT_FILE"
grep -q '^        service_start_failed$' "$SCRIPT_FILE"
grep -q 'caddy reload --config "\$TARGET_CONFIG" --adapter caddyfile$' "$SCRIPT_FILE"
grep -q '^  reload)$' "$SCRIPT_FILE"
grep -q '^      fail "Caddy service is not running; run scripts/macos/caddy-service start first"$' "$SCRIPT_FILE"
grep -q 'The managed Caddy listener port is already in use' "$SCRIPT_FILE"
grep -q 'caddy reload --config "\$TARGET_CONFIG" --adapter caddyfile$' "$SCRIPT_FILE"
grep -q '^  status)$' "$SCRIPT_FILE"
grep -q 'brew services info "\$CADDY_SERVICE_NAME"$' "$SCRIPT_FILE"
echo "Caddy service checks passed"
