#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
README="$ROOT/README.md"

test -f "$README"
test -f "$ROOT/docs/macos/caddy.md"
test -f "$ROOT/docs/macos/podman.md"
test -f "$ROOT/docs/macos/system.md"
test -f "$ROOT/config/podman/shared-macos.conf"
test -f "$ROOT/config/repo/shared.conf"

grep -q '`podman/`' "$README"
grep -q '`config/podman/`' "$README"
grep -q '`config/repo/`' "$README"
grep -q '`scripts/macos/brew-configure`' "$README"
grep -q '`scripts/macos/caddy-trust`' "$README"
grep -q '`scripts/macos/brew-service`' "$README"
grep -q '`scripts/macos/brew-bootstrap`' "$README"
grep -q '`~/.config/containers/containers.conf`' "$README"
grep -q '`docs/macos/caddy.md`' "$README"
grep -q '`docs/macos/podman.md`' "$README"
grep -q '`docs/macos/system.md`' "$README"
grep -q '`scripts/macos/system-configure`' "$README"
grep -q '`scripts/macos/system-configure`' "$ROOT/docs/macos/system.md"
grep -q 'brew-configure' "$ROOT/docs/macos/system.md"
grep -q 'system-configure' "$ROOT/docs/macos/system.md"
grep -q '`config/brew/shared-macos.Brewfile`' "$README"
grep -q '`config/brew/<host>-macos.Brewfile`' "$README"
grep -q 'Layered config' "$README"
grep -q '`config/podman/containers.conf`' "$ROOT/docs/macos/podman.md"
grep -q '`PODMAN_MACHINE_NAME_DEFAULT`' "$ROOT/docs/macos/podman.md"
grep -q 'fails clearly' "$ROOT/docs/macos/podman.md"
grep -q 'asks for approval' "$ROOT/docs/macos/podman.md"
grep -q 'bypassed by user choice' "$ROOT/docs/macos/podman.md"
grep -q 'disk_size' "$ROOT/docs/macos/podman.md"
grep -q 'grow-only managed setting' "$ROOT/docs/macos/podman.md"
grep -q '`config/podman/shared-macos.conf`' "$ROOT/docs/macos/podman.md"
grep -q '`PODMAN_DIAGNOSE_OUTPUT_DIR`' "$ROOT/docs/macos/podman.md"
grep -q '`PODMAN_DIAGNOSE_EVENT_WINDOWS`' "$ROOT/docs/macos/podman.md"
grep -q '`PODMAN_DIAGNOSE_HOST_COMMANDS`' "$ROOT/docs/macos/podman.md"
grep -q '`PODMAN_DIAGNOSE_MACHINE_COMMANDS`' "$ROOT/docs/macos/podman.md"
grep -q 'relative path' "$ROOT/docs/macos/podman.md"
grep -q 'absolute path' "$ROOT/docs/macos/podman.md"
grep -q '`config/caddy/shared-macos.Caddyfile`' "$ROOT/docs/macos/caddy.md"
grep -q '`scripts/macos/caddy-configure`' "$ROOT/docs/macos/caddy.md"
grep -q '`scripts/macos/brew-service start`' "$ROOT/docs/macos/caddy.md"
grep -q '`https://127.0.0.1:8123`' "$ROOT/docs/macos/caddy.md"
grep -q '`config/system/shared-macos.conf`' "$ROOT/docs/macos/system.md"
grep -q '`scripts/macos/system-configure`' "$ROOT/docs/macos/system.md"

echo "Documentation checks passed"
