#!/usr/bin/env bash
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
SCRIPT_FILE="$ROOT/scripts/macos/nushell-configure"
TOOLING_NU="$ROOT/config/nushell/installations-configurations.nu"
test -f "$SCRIPT_FILE"
test -f "$TOOLING_NU"
grep -q '^\$env.FZF_DEFAULT_OPTS = ' "$TOOLING_NU"
grep -q '^source "__NUSHELL_DIR__/zoxide.nu"$' "$TOOLING_NU"
grep -q '^source "__NUSHELL_DIR__/atuin.nu"$' "$TOOLING_NU"
grep -q '^source "__NUSHELL_DIR__/starship.nu"$' "$TOOLING_NU"
grep -q '^source "__NUSHELL_DIR__/completions-jj.nu"$' "$TOOLING_NU"
grep -q '^alias cat = bat --paging=never --style=plain$' "$TOOLING_NU"
grep -q '^def ll \[\] {$' "$TOOLING_NU"
grep -q '^def fe \[\] {$' "$TOOLING_NU"
grep -q '^TARGET_DIR="\${1:-\${XDG_CONFIG_HOME:-\$HOME/.config}/nushell}"$' "$SCRIPT_FILE"
grep -q '^AUTOLOAD_DIR="\$TARGET_DIR/autoload"$' "$SCRIPT_FILE"
grep -q '^COMPAT_PATH="\${NUSHELL_MACOS_COMPAT_PATH:-\$HOME/Library/Application Support/nushell}"$' "$SCRIPT_FILE"
grep -q '^generate_file "\$TARGET_DIR/atuin.nu" "atuin Nushell integration"' "$SCRIPT_FILE"
grep -q '^generate_file "\$TARGET_DIR/starship.nu" "starship Nushell integration"' "$SCRIPT_FILE"
grep -q '^  log_change "Configuration" "Nushell compatibility symlink" "\$change_name" "\$compat_path" "Linked macOS Application Support to the managed ~/.config/nushell tree"$' "$SCRIPT_FILE"
echo "Nushell config checks passed"
