#!/usr/bin/env bash
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
SCRIPT_FILE="$ROOT/scripts/macos/podman-configure"
test -f "$ROOT/config/podman/containers.conf"
test -f "$ROOT/config/podman/shared-macos.conf"
test -f "$SCRIPT_FILE"
grep -q 'scripts/macos/brew-bootstrap' "$ROOT/scripts/macos/podman-check"
grep -q 'may pull the configured verification image' "$ROOT/scripts/macos/podman-check"
grep -q '^PODMAN_DIAGNOSE_OUTPUT_DIR=' "$ROOT/config/podman/shared-macos.conf"
grep -q '^PODMAN_DIAGNOSE_EVENT_WINDOWS=' "$ROOT/config/podman/shared-macos.conf"
grep -q '^PODMAN_DIAGNOSE_HOST_COMMANDS=' "$ROOT/config/podman/shared-macos.conf"
grep -q 'Usage: .*\[diagnose\]' "$ROOT/scripts/macos/podman-check"
grep -q '^run_diagnose() {$' "$ROOT/scripts/macos/podman-check"
grep -q '^print_diagnose_summary() {$' "$ROOT/scripts/macos/podman-check"
grep -q '^\[machine\]$' "$ROOT/config/podman/containers.conf"
grep -q '^cpus=4$' "$ROOT/config/podman/containers.conf"
grep -q '^memory=8192$' "$ROOT/config/podman/containers.conf"
grep -q '^disk_size=60$' "$ROOT/config/podman/containers.conf"
grep -q '^rootful=false$' "$ROOT/config/podman/containers.conf"
grep -q '^PODMAN_MACHINE_NAME_DEFAULT=' "$ROOT/config/podman/shared-macos.conf"
grep -q '^PODMAN_CHECK_IMAGE="docker.io/library/alpine:3.22"$' "$ROOT/config/podman/shared-macos.conf"
grep -q '^load_machine_set_help() {$' "$SCRIPT_FILE"
grep -q '^apply_planned_machine_preferences() {$' "$SCRIPT_FILE"
grep -q '^machine_set_option_supported() {$' "$SCRIPT_FILE"
grep -q '^apply_machine_setting() {$' "$SCRIPT_FILE"
grep -q '^machine_is_running() {$' "$SCRIPT_FILE"
grep -q '^plan_machine_preferences() {$' "$SCRIPT_FILE"
grep -q '^print_machine_settings_diff() {$' "$SCRIPT_FILE"
grep -q '^bypass_machine_reconciliation() {$' "$SCRIPT_FILE"
grep -q '^prepare_machine_for_update() {$' "$SCRIPT_FILE"
grep -q '^restore_machine_after_update() {$' "$SCRIPT_FILE"
grep -q '^load_podman_config() {$' "$SCRIPT_FILE"
grep -q '^prompt_yes_no() {$' "$ROOT/lib/shell/common.sh"
grep -q 'Defaults to the configured machine name' "$ROOT/scripts/macos/podman-configure"
grep -q '^  fail "podman is not installed; run scripts/macos/brew-install first"$' "$SCRIPT_FILE"
grep -q '^  podman machine init "\${MACHINE_INIT_ARGS\[@\]}" "\$MACHINE_NAME"$' "$SCRIPT_FILE"
grep -q '^  podman machine start "\$MACHINE_NAME"$' "$SCRIPT_FILE"
echo "Podman checks passed (repository-only coverage)"
