#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
CONFIG_FILE="$ROOT/config/git/maldoria.conf"
SCRIPT_FILE="$ROOT/scripts/macos/git-configure"
COMMON_FILE="$ROOT/lib/shell/common.sh"

test -f "$CONFIG_FILE"
test -f "$SCRIPT_FILE"
test -f "$COMMON_FILE"
grep -q '^sign|maldoria-github-ezirius-sign|ssh-ed25519 ' "$CONFIG_FILE"
grep -q '^repo|installations-configurations|maldoria-github-ezirius-installations-configurations|ssh-ed25519 ' "$CONFIG_FILE"
grep -q '^repo|nix-configurations|maldoria-github-ezirius-nix-configurations|ssh-ed25519 ' "$CONFIG_FILE"
grep -q '^repo|opencode-container|maldoria-github-ezirius-opencode-container|ssh-ed25519 ' "$CONFIG_FILE"
grep -q '^repo|honcho-container|maldoria-github-ezirius-honcho-container|ssh-ed25519 ' "$CONFIG_FILE"
grep -q '^repo|hermes-agent-container|maldoria-github-ezirius-hermes-agent-container|ssh-ed25519 ' "$CONFIG_FILE"
grep -q '^repo|openclaw-container|maldoria-github-ezirius-openclaw-container|ssh-ed25519 ' "$CONFIG_FILE"
grep -q '^canonicalize_path() {$' "$COMMON_FILE"
grep -q '^require_git_repo_path() {$' "$COMMON_FILE"
grep -q '^require_nonempty_name() {$' "$SCRIPT_FILE"
grep -q 'sed -E '\''s/\[^a-z0-9\]+/-/g; s/\^-+//; s/-+\$//'\''' "$SCRIPT_FILE"
grep -q 'REPO_ROOT="\$(canonicalize_path "\$REPO_ROOT_OVERRIDE")"' "$SCRIPT_FILE"
grep -q 'require_git_repo_path "\$REPO_ROOT"' "$SCRIPT_FILE"
grep -q 'require_nonempty_name "\$HOST_NAME" "Host name"' "$SCRIPT_FILE"
grep -q 'require_nonempty_name "\$REPO_NAME" "Repo name"' "$SCRIPT_FILE"
grep -q 'change_name="Created"' "$SCRIPT_FILE"
grep -q 'change_name="Updated"' "$SCRIPT_FILE"
echo "Git host config checks passed"
