#!/usr/bin/env bash
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
CONFIG_FILE="$ROOT/config/ghostty/installations-configurations.ghostty"
SCRIPT_FILE="$ROOT/scripts/macos/ghostty-configure"
test -f "$CONFIG_FILE"
test -f "$SCRIPT_FILE"
grep -q '^command = __NU_PATH__$' "$CONFIG_FILE"
grep -q '^background = 1a1b26$' "$CONFIG_FILE"
grep -q '^foreground = c0caf5$' "$CONFIG_FILE"
grep -q '^  usage_error "\$(basename "\$0") takes at most 1 argument: \[config-dir\]"$' "$SCRIPT_FILE"
grep -q '^TARGET_CONFIG_DIR="\${1:-\${XDG_CONFIG_HOME:-\$HOME/.config}/ghostty}"$' "$SCRIPT_FILE"
grep -q '^TARGET_INCLUDE="\$TARGET_CONFIG_DIR/installations-configurations.ghostty"$' "$SCRIPT_FILE"
grep -q '^INCLUDE_DIRECTIVE=' "$SCRIPT_FILE"
grep -q 'log_change "Configuration" "Ghostty config" ' "$SCRIPT_FILE"
grep -q 'log_change "Configuration" "Ghostty config include" ' "$SCRIPT_FILE"
echo "Ghostty config checks passed"
