REPO_PLATFORM_DARWIN="macos"
REPO_PLATFORM_LINUX="linux"
REPO_SHARED_REPO_PATTERN="%s/%s/shared/%s-shared.%s"
REPO_SHARED_PLATFORM_PATTERN="%s/%s/%s/%s-shared.%s"
REPO_HOST_PLATFORM_PATTERN="%s/%s/%s/%s-%s.%s"
REPO_HOMEBREW_PRIMARY_PREFIX="/opt/homebrew"
REPO_HOMEBREW_SECONDARY_PREFIX="/usr/local"
