CADDY_RUNTIME_RELATIVE_PATH="etc/Caddyfile"
CADDY_SERVICE_NAME="caddy"
CADDY_TRUST_CERT_NAME="Caddy Local Authority"
CADDY_TRUST_KEYCHAINS=(
  "/Library/Keychains/System.keychain"
  "$HOME/Library/Keychains/login.keychain-db"
)
